[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.118.0",
    "httpx>=0.28.1",
    "pydantic>=2.11.9",
    "pytest>=8.4.2",
    "python-dateutil>=2.9.0.post0",
    "uvicorn>=0.37.0",
]
